apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  type: LoadBalancer
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
  loadBalancerIP: 192.168.178.225
